### ISSUE TITLE
Erroneous "Twitter API is down" message

### ISSUE THREAD

**Issue by peterdeutsch** [bfbachmann/Silver-Screen#39]
I occasionally find that I encounter "Twitter API is down" errors when I'm developing. I believe these to be caused by errors during the processing stage (which are resolved through development), but they aren't related to the Twitter API. We should make sure that the "Twitter API is down" message is only shown for API errors, not otherwise.

**Comment by bfbachmann** [comment]
"Cannot connect to twitter" is displayed with an addition error message:

``` python
try:
    raw_tweets = twitter.search_movie(movie)
except Exception as error:
    if type(error) is ValueError:
        print('ERROR: Rate limit exceeded')
        data_to_render['error_message'] = 'Sorry, SilverScreen\'s Twitter API rate limit has been exceeded. Please try a different movie, or try again later.'
    else:
        print('ERROR: cannot connect to Twitter: ' + str(error))
        data_to_render['error_message'] = 'Sorry, connection to Twitter failed. The Twitter API might be down. Please try again later.'
 return render(request, 'error.html', data_to_render)
```
