### ISSUE TITLE
Sentiment Analysis should not take movie title into account

### ISSUE THREAD

**Issue by bfbachmann** [bfbachmann/Silver-Screen#5]
Currently our sentiment analysis algorithm takes the name of the movie into account when analyzing the sentiment of each tweet. It should filter out the title because of the effect the title could have on the sentiment score for that tweet. Here is an example of where this ruins our data:

![image](https://cloud.githubusercontent.com/assets/9647946/19952866/a5015c3a-a125-11e6-8b3a-e8d0f539ce31.png)

**Comment by roryjf** [comment]
Good point. We'd have to do this pre-sentiment analysis - we would feed the tweet stripped of the movie title into the sentiment analysis engine.

**Comment by roryjf** [comment]
Suicide is a super negative word, haha.

**Comment by bfbachmann** [comment]
Fixed
